### ISSUE TITLE
Be able to see all of the open issues in that repository

### ISSUE THREAD

**Issue by shouston3** [gitodoro/gitodoro#10]
(After clicking on my desired repository)

And potentially all of the labels (and number of comments?) for the issue in question

- select field populated with a list of issues
- on selecting an issue, show the timer

- Github API - https://developer.github.com/v3/issues/#list-issues-for-a-repository

**Comment by Jbarget** [comment]
Github API - https://developer.github.com/v3/issues/#list-issues-for-a-repository

**Comment by Jbarget** [comment]
@shouston3 not sure what you mean by:
>And potentially all of the labels (and number of comments?) for the issue in question

**Comment by shouston3** [comment]
Sorry, sometimes I can be quite bad with my wording of issues.

As a user after clicking on my desired repository, I will see a view of all of the open issues for that repository.

This view of the issues should also display next to each issue all of the labels attached to each issue
(We could also include other meta information next to each issue such as number of comments or date opened)
