### ISSUE TITLE
Elm or Plain JS

### ISSUE THREAD

**Issue by Jbarget** [gitodoro/gitodoro#3]
Are we using this as an opportunity to learn Elm or we going to stick with JS?

**Comment by shouston3** [comment]
I'm up for trying a bit of elm

**Comment by Jbarget** [comment]
The question on my mind is learning curve vs the time we have over the holiday period. Im unsure of how much time i'll have to dedicate to this after starting work in the new year so a good target would be to have an MVP around the 6th Jan

**Comment by shouston3** [comment]
I agree, sorry I was mid edit of my comment when yours got posted.

So no elm

**Comment by Jbarget** [comment]
Just wanted to get @JMurphyWeb's view on it before deciding

**Comment by shouston3** [comment]
Can you close this @JMurphyWeb

**Comment by JMurphyWeb** [comment]
Seems like a good shout.
