### ISSUE TITLE
all assertions within shot.inject callback pass

### ISSUE THREAD

**Issue by Jbarget** [gitodoro/gitodoro#47]
linked to #46

```
describe('Express server', () => {
  it('/ - should respond with a 200 and an html page', () => {
    const request = {
      method: 'GET',
      url: '/'
    };

    shot.inject(app, request, (res) => {
      console.log(res.statusCode); // 200
      assert.equal(res.statusCode, 100);
    });
  });
});
```

With the above tests the `res.statusCode` comes back as `200` and asserting it to be `100` still passes

**Comment by shouston3** [comment]
Your formatting the testing wrong, the `assert.equal` syntax is wrong. Ill push up the correct way of doing it

**Comment by shouston3** [comment]
You need to tell the `it` statement when it's finished.

Try this instead:

```
it('/ - should respond with a 200 and an html page', (done) => {
    const request = {
      method: 'GET',
      url: '/'
    };

    shot.inject(app, request, (res) => {
      console.log(res.statusCode); // 200
      assert.equal(res.statusCode, 100);
      done();
    });
  });
```

**Comment by Jbarget** [comment]
Tried but didn't make a difference, did that work for you?

**Comment by shouston3** [comment]
Yea works

**Comment by shouston3** [comment]
If we get the tests hosted then we have one version of truth

**Comment by shouston3** [comment]
@Jbarget Working tests in [pr](https://github.com/gitodoro/gitodoro/pull/49)
