### ISSUE TITLE
api endpoints

### ISSUE THREAD

**Issue by Jbarget** [gitodoro/gitodoro#54]
At the moment the wiki API endpoints dont seem to follow a pattern. I think its a good convention for your API request `method` + `url` to be *meaningful*.

I propose (changes in **bold**):

GET - /orgs : gets all organisations of authenticated user
**GET - /repos/{org_id} : gets all repos of an organisation**
**GET - /issues/{repo_id} : gets all issues of an organisation**
~~GET~~ POST- /issue/{issue_id}/start : adds `in-progress` label
~~GET~~ POST- /issue/{issue_id}/stop : removes `in-progress` label

**Comment by shouston3** [comment]
Why do are the last 2 `get` requests?

**Comment by shouston3** [comment]
*gets all issues of a repo

**Comment by shouston3** [comment]
Looks good. I've opened an issue to implement this in the wiki #55
