### ISSUE TITLE
expect({statusCode}) doesnt work

### ISSUE THREAD

**Issue by Jbarget** [gitodoro/gitodoro#72]
seems that the expecting of a status code doesnt affect the test

**Comment by shouston3** [comment]
Yea strange, I think I've implemented the format that supertest wants from the docs

**Comment by shouston3** [comment]
@Jbarget I'm up for just deleting this status code part from the "expect chain" and instead just checking `res.status === <statusCode>` in the last "end chain" part

**Comment by Jbarget** [comment]
@shouston3 sounds like a good alternative!

**Comment by Jbarget** [comment]
@shouston3 reopening this as we need to change some more: 
eg. https://github.com/gitodoro/gitodoro/blob/master/test/api/specs/github.spec.js#L19

**Comment by shouston3** [comment]
So I left that one in since when I changed that value the tests broke so the test is actually working, but changing it for the sake of consistent syntax makes sense

**Comment by shouston3** [comment]
Actually consistent more readable syntax is more important, implementing.

Good spot @Jbarget 

Opened pr #87 to close this
