### ISSUE TITLE
Be able to easily search through my repositories

### ISSUE THREAD

**Issue by shouston3** [gitodoro/gitodoro#9]
Either by the repos being organised by organisation, or with a search and autocomplete functionality

- select field populated with a list of user's Github repos (front-end)
- on selecting a repo send request for issues within that repo
- Github API - https://developer.github.com/v3/repos/#list-your-repositories

**Comment by Jbarget** [comment]
Github API - https://developer.github.com/v3/repos/#list-your-repositories
